import 'dart:async';
import 'package:flutter/foundation.dart';
import '../../core/app_logger.dart';
import 'models/strategy_listing.dart';
import '../../domain/trade_signal.dart';
import '../../domain/order.dart'; // For OrderSide

/// Service handles the Strategy Marketplace.
///
/// Allows users to:
/// - Browse strategies ([getFeaturedStrategies], [searchStrategies])
/// - Subscribe to strategies ([subscribeToStrategy])
/// - Publish their own strategies ([publishStrategy])
///
/// Currently uses MOCK data for Phase 4B.
class MarketplaceService extends ChangeNotifier {
  /// Published strategy listings.
  ///
  /// Intentionally starts EMPTY. This used to be seeded with invented
  /// strategies carrying invented performance ("+312.5% return", "98% win
  /// rate", "$99/month") presented as though they were real products for sale
  /// — indefensible in a tool whose whole promise is honest numbers. The
  /// marketplace now shows only strategies a user has actually published.
  final List<StrategyListing> _mockListings = [];

  final Set<String> _subscriptions = {}; // Set of Strategy IDs

  /// Get featured strategies for the home carousel
  Future<List<StrategyListing>> getFeaturedStrategies() async {
    await Future.delayed(const Duration(milliseconds: 600)); // Simulate network
    return _mockListings;
  }

  /// Search strategies by query or category
  Future<List<StrategyListing>> searchStrategies({
    String? query,
    StrategyCategory? category,
  }) async {
    await Future.delayed(const Duration(milliseconds: 400));
    return _mockListings.where((s) {
      if (category != null && s.category != category) return false;
      if (query != null &&
          !s.title.toLowerCase().contains(query.toLowerCase())) {
        return false;
      }
      return true;
    }).toList();
  }

  /// Subscribe to a strategy
  /// Returns success status
  Future<bool> subscribeToStrategy(String strategyId) async {
    AppLogger.info("MARKET: Subscribing to $strategyId...");
    await Future.delayed(
        const Duration(seconds: 1)); // Simulate payment processing

    // In a real app, this would trigger IAP or Credit deduction
    _subscriptions.add(strategyId);
    notifyListeners();

    AppLogger.info("MARKET: Subscribed to $strategyId successfully.");
    return true;
  }

  /// Check if user is subscribed
  bool isSubscribed(String strategyId) {
    return _subscriptions.contains(strategyId);
  }

  /// Check if user is subscribed by Strategy Name (For Phase 4C Mock)
  bool isSubscribedByName(String strategyName) {
    try {
      final strat = _mockListings.firstWhere((s) => s.title == strategyName);
      return _subscriptions.contains(strat.id);
    } catch (e) {
      return false;
    }
  }

  /// Publish a new strategy
  Future<void> publishStrategy(StrategyListing listing) async {
    AppLogger.info("MARKET: Publishing ${listing.title}...");
    await Future.delayed(const Duration(seconds: 2));
    _mockListings.add(listing);
    notifyListeners();
    AppLogger.info("MARKET: Published successfully.");
  }

  // --- Signal Simulation (Phase 4C) ---
  final _signalController = StreamController<TradeSignal>.broadcast();
  Stream<TradeSignal> get signalStream => _signalController.stream;
  Timer? _simTimer;

  /// Start broadcasting mock signals for subscribed strategies
  void startSignalSimulation() {
    _simTimer?.cancel();
    _simTimer = Timer.periodic(const Duration(seconds: 10), (timer) {
      if (_subscriptions.isEmpty) return;

      // Pick a random strategy to emit a signal
      // In reality, this would come from a websocket
      final randomStratId = _subscriptions.toList().first;
      // The listing may no longer exist (nothing is seeded any more), so bail
      // out rather than throwing inside a periodic timer.
      final matches =
          _mockListings.where((s) => s.id == randomStratId).toList();
      if (matches.isEmpty) return;
      final strat = matches.first;

      final signal = TradeSignal(
        timestamp: DateTime.now(),
        price: 42000.0 + (timer.tick * 10), // variable price
        side: (timer.tick % 2 == 0) ? OrderSide.buy : OrderSide.sell,
        strategyName: strat.title,
        description: "Signal generated by ${strat.title} algorithm.",
      );

      _signalController.add(signal);
      AppLogger.info("MARKET: Emitted signal for ${strat.title}");
    });
  }

  @override
  void dispose() {
    _simTimer?.cancel();
    _signalController.close();
    super.dispose();
  }
}

extension StrategyListingCopy on StrategyListing {
  StrategyListing copyWith({
    String? title,
    String? description,
    double? monthlyPrice,
    MarketplaceTier? tier,
    double? totalReturn,
    double? winRate,
    double? rating,
  }) {
    return StrategyListing(
      id: id,
      authorId: authorId,
      authorName: authorName,
      title: title ?? this.title,
      description: description ?? this.description,
      category: category,
      monthlyPrice: monthlyPrice ?? this.monthlyPrice,
      tier: tier ?? this.tier,
      totalReturn: totalReturn ?? this.totalReturn,
      winRate: winRate ?? this.winRate,
      maxDrawdown: maxDrawdown,
      subscriberCount: subscriberCount,
      rating: rating ?? this.rating,
      verified: verified,
      createdAt: createdAt,
      lastUpdated: lastUpdated,
    );
  }
}
