import 'dart:async';
import 'package:flutter/foundation.dart';
import '../../domain/candle_model.dart';
import '../../domain/trade_signal.dart';
// [NEW] For OrderSide
import '../../core/app_logger.dart';
import 'sandbox_kernel.dart'; // [NEW] Pure Dart Kernel

/// Service responsible for "Hyper-Threaded" execution of user scripts.
/// Uses Dart Isolates to run the simulation on a separate CPU core.
class PythonSandboxService {
  /// Simulates a Python strategy on the provided history.
  /// Returns a list of TradeSignals generated by the script.
  Future<List<TradeSignal>> simulateStrategy({
    required String script,
    required List<Candle> history,
  }) async {
    AppLogger.info("SANDBOX: Spawning Hyper-Thread for simulation...");

    // Spawns a background isolate to keep UI 120FPS smooth
    return await compute(
        executeStrategyKernel, SimulationRequest(script, history));
  }
}
