// Mocks generated by Mockito 5.4.4 from annotations
// in volex_terminal/test/unit/engine/backtest_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:volex_terminal/engine/persistence/persistence_service.dart'
    as _i5;
import 'package:volex_terminal/engine/persistence/secure_persistence_service.dart'
    as _i2;
import 'package:volex_terminal/engine/risk_manager.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSecurePersistenceService_0 extends _i1.SmartFake
    implements _i2.SecurePersistenceService {
  _FakeSecurePersistenceService_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [RiskManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockRiskManager extends _i1.Mock implements _i3.RiskManager {
  MockRiskManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isManualOnlyMode => (super.noSuchMethod(
        Invocation.getter(#isManualOnlyMode),
        returnValue: false,
      ) as bool);

  @override
  set isManualOnlyMode(bool? _isManualOnlyMode) => super.noSuchMethod(
        Invocation.setter(
          #isManualOnlyMode,
          _isManualOnlyMode,
        ),
        returnValueForMissingStub: null,
      );

  @override
  double get maxDailyLoss => (super.noSuchMethod(
        Invocation.getter(#maxDailyLoss),
        returnValue: 0.0,
      ) as double);

  @override
  double get maxPositionSizePercent => (super.noSuchMethod(
        Invocation.getter(#maxPositionSizePercent),
        returnValue: 0.0,
      ) as double);

  @override
  double get maxTotalExposurePercent => (super.noSuchMethod(
        Invocation.getter(#maxTotalExposurePercent),
        returnValue: 0.0,
      ) as double);

  @override
  int get maxOpenPositions => (super.noSuchMethod(
        Invocation.getter(#maxOpenPositions),
        returnValue: 0,
      ) as int);

  @override
  bool get isLocked => (super.noSuchMethod(
        Invocation.getter(#isLocked),
        returnValue: false,
      ) as bool);

  @override
  _i4.Stream<bool> get safetyStream => (super.noSuchMethod(
        Invocation.getter(#safetyStream),
        returnValue: _i4.Stream<bool>.empty(),
      ) as _i4.Stream<bool>);

  @override
  Map<String, _i3.StrategyAuthorization> get authorizedStrategies =>
      (super.noSuchMethod(
        Invocation.getter(#authorizedStrategies),
        returnValue: <String, _i3.StrategyAuthorization>{},
      ) as Map<String, _i3.StrategyAuthorization>);

  @override
  double get maxAggregateRiskUsdt => (super.noSuchMethod(
        Invocation.getter(#maxAggregateRiskUsdt),
        returnValue: 0.0,
      ) as double);

  @override
  double get currentAggregateRiskUsdt => (super.noSuchMethod(
        Invocation.getter(#currentAggregateRiskUsdt),
        returnValue: 0.0,
      ) as double);

  @override
  _i4.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void authorizeStrategy(
    String? id,
    _i3.StrategyAuthorization? config,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #authorizeStrategy,
          [
            id,
            config,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void revokeStrategy(String? id) => super.noSuchMethod(
        Invocation.method(
          #revokeStrategy,
          [id],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setMaxAggregateRisk(double? limit) => super.noSuchMethod(
        Invocation.method(
          #setMaxAggregateRisk,
          [limit],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setDailyLossLimit(double? limit) => super.noSuchMethod(
        Invocation.method(
          #setDailyLossLimit,
          [limit],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setMaxOrderSize(double? limit) => super.noSuchMethod(
        Invocation.method(
          #setMaxOrderSize,
          [limit],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void activateEmergencyStop() => super.noSuchMethod(
        Invocation.method(
          #activateEmergencyStop,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void reset() => super.noSuchMethod(
        Invocation.method(
          #reset,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool validateOrder({
    required double? quantity,
    required double? priceUsdt,
    String? strategyId,
    bool? isLive = false,
    bool? isReduction = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #validateOrder,
          [],
          {
            #quantity: quantity,
            #priceUsdt: priceUsdt,
            #strategyId: strategyId,
            #isLive: isLive,
            #isReduction: isReduction,
          },
        ),
        returnValue: false,
      ) as bool);

  @override
  void incrementStrategyTradeCount(String? strategyId) => super.noSuchMethod(
        Invocation.method(
          #incrementStrategyTradeCount,
          [strategyId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void recordTradeResult(
    double? pnlUsdt, {
    String? strategyId,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #recordTradeResult,
          [pnlUsdt],
          {#strategyId: strategyId},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateAggregateRisk(double? deltaUsdt) => super.noSuchMethod(
        Invocation.method(
          #updateAggregateRisk,
          [deltaUsdt],
        ),
        returnValueForMissingStub: null,
      );

  @override
  Map<String, dynamic> getStatus() => (super.noSuchMethod(
        Invocation.method(
          #getStatus,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [PersistenceService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPersistenceService extends _i1.Mock
    implements _i5.PersistenceService {
  MockPersistenceService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SecurePersistenceService get secure => (super.noSuchMethod(
        Invocation.getter(#secure),
        returnValue: _FakeSecurePersistenceService_0(
          this,
          Invocation.getter(#secure),
        ),
      ) as _i2.SecurePersistenceService);

  @override
  _i4.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  String? getString(String? key) => (super.noSuchMethod(Invocation.method(
        #getString,
        [key],
      )) as String?);

  @override
  _i4.Future<void> setString(
    String? key,
    String? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setString,
          [
            key,
            value,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  List<String>? getStringList(String? key) =>
      (super.noSuchMethod(Invocation.method(
        #getStringList,
        [key],
      )) as List<String>?);

  @override
  _i4.Future<void> setStringList(
    String? key,
    List<String>? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setStringList,
          [
            key,
            value,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  int? getInt(String? key) => (super.noSuchMethod(Invocation.method(
        #getInt,
        [key],
      )) as int?);

  @override
  _i4.Future<void> setInt(
    String? key,
    int? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setInt,
          [
            key,
            value,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  bool? getBool(String? key) => (super.noSuchMethod(Invocation.method(
        #getBool,
        [key],
      )) as bool?);

  @override
  _i4.Future<void> setBool(
    String? key,
    bool? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setBool,
          [
            key,
            value,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> saveSetting<T>(
    String? key,
    T? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveSetting,
          [
            key,
            value,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  T? getSetting<T>(
    String? key, {
    T? defaultValue,
  }) =>
      (super.noSuchMethod(Invocation.method(
        #getSetting,
        [key],
        {#defaultValue: defaultValue},
      )) as T?);

  @override
  _i4.Future<void> saveState<T>(
    String? key,
    T? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveState,
          [
            key,
            value,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  T? getState<T>(
    String? key, {
    T? defaultValue,
  }) =>
      (super.noSuchMethod(Invocation.method(
        #getState,
        [key],
        {#defaultValue: defaultValue},
      )) as T?);

  @override
  _i4.Future<void> saveList(
    String? boxName,
    List<dynamic>? items,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveList,
          [
            boxName,
            items,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  List<dynamic> getList(String? boxName) => (super.noSuchMethod(
        Invocation.method(
          #getList,
          [boxName],
        ),
        returnValue: <dynamic>[],
      ) as List<dynamic>);

  @override
  _i4.Future<void> clearAll() => (super.noSuchMethod(
        Invocation.method(
          #clearAll,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> flushState() => (super.noSuchMethod(
        Invocation.method(
          #flushState,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
