// Mocks generated by Mockito 5.4.4 from annotations
// in volex_terminal/test/unit/engine/execution_manager_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:volex_terminal/data/binance/binance_api_service.dart' as _i3;
import 'package:volex_terminal/domain/candle_model.dart' as _i6;
import 'package:volex_terminal/domain/order.dart' as _i2;
import 'package:volex_terminal/domain/symbol_info.dart' as _i7;
import 'package:volex_terminal/engine/risk_manager.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeOrder_0 extends _i1.SmartFake implements _i2.Order {
  _FakeOrder_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [BinanceApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBinanceApiService extends _i1.Mock implements _i3.BinanceApiService {
  MockBinanceApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get apiKey => (super.noSuchMethod(
        Invocation.getter(#apiKey),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#apiKey),
        ),
      ) as String);

  @override
  String get apiSecret => (super.noSuchMethod(
        Invocation.getter(#apiSecret),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#apiSecret),
        ),
      ) as String);

  @override
  _i5.Future<List<_i6.Candle>> getKlines(
    _i7.SymbolInfo? symbol,
    String? interval, {
    int? limit = 500,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getKlines,
          [
            symbol,
            interval,
          ],
          {#limit: limit},
        ),
        returnValue: _i5.Future<List<_i6.Candle>>.value(<_i6.Candle>[]),
      ) as _i5.Future<List<_i6.Candle>>);

  @override
  _i5.Future<_i2.Order> placeOrder({
    required _i7.SymbolInfo? symbol,
    required String? side,
    required double? quantity,
    double? price,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #placeOrder,
          [],
          {
            #symbol: symbol,
            #side: side,
            #quantity: quantity,
            #price: price,
          },
        ),
        returnValue: _i5.Future<_i2.Order>.value(_FakeOrder_0(
          this,
          Invocation.method(
            #placeOrder,
            [],
            {
              #symbol: symbol,
              #side: side,
              #quantity: quantity,
              #price: price,
            },
          ),
        )),
      ) as _i5.Future<_i2.Order>);

  @override
  _i5.Future<void> cancelOrder(
    String? orderId,
    _i7.SymbolInfo? symbol,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelOrder,
          [
            orderId,
            symbol,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<Map<String, double>> getBalances() => (super.noSuchMethod(
        Invocation.method(
          #getBalances,
          [],
        ),
        returnValue: _i5.Future<Map<String, double>>.value(<String, double>{}),
      ) as _i5.Future<Map<String, double>>);

  @override
  _i5.Future<List<_i2.Order>> getOpenOrders(_i7.SymbolInfo? symbol) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOpenOrders,
          [symbol],
        ),
        returnValue: _i5.Future<List<_i2.Order>>.value(<_i2.Order>[]),
      ) as _i5.Future<List<_i2.Order>>);

  @override
  _i5.Future<List<Map<String, dynamic>>> getPositions() => (super.noSuchMethod(
        Invocation.method(
          #getPositions,
          [],
        ),
        returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Stream<_i6.Candle> subscribeToKlines(
    _i7.SymbolInfo? symbol,
    String? interval,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #subscribeToKlines,
          [
            symbol,
            interval,
          ],
        ),
        returnValue: _i5.Stream<_i6.Candle>.empty(),
      ) as _i5.Stream<_i6.Candle>);

  @override
  _i5.Stream<Map<String, dynamic>> subscribeToUserData() => (super.noSuchMethod(
        Invocation.method(
          #subscribeToUserData,
          [],
        ),
        returnValue: _i5.Stream<Map<String, dynamic>>.empty(),
      ) as _i5.Stream<Map<String, dynamic>>);

  @override
  _i5.Future<dynamic> getAccountInfo() => (super.noSuchMethod(
        Invocation.method(
          #getAccountInfo,
          [],
        ),
        returnValue: _i5.Future<dynamic>.value(),
      ) as _i5.Future<dynamic>);
}

/// A class which mocks [RiskManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockRiskManager extends _i1.Mock implements _i8.RiskManager {
  MockRiskManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isManualOnlyMode => (super.noSuchMethod(
        Invocation.getter(#isManualOnlyMode),
        returnValue: false,
      ) as bool);

  @override
  set isManualOnlyMode(bool? _isManualOnlyMode) => super.noSuchMethod(
        Invocation.setter(
          #isManualOnlyMode,
          _isManualOnlyMode,
        ),
        returnValueForMissingStub: null,
      );

  @override
  double get maxDailyLoss => (super.noSuchMethod(
        Invocation.getter(#maxDailyLoss),
        returnValue: 0.0,
      ) as double);

  @override
  double get maxPositionSizePercent => (super.noSuchMethod(
        Invocation.getter(#maxPositionSizePercent),
        returnValue: 0.0,
      ) as double);

  @override
  double get maxTotalExposurePercent => (super.noSuchMethod(
        Invocation.getter(#maxTotalExposurePercent),
        returnValue: 0.0,
      ) as double);

  @override
  int get maxOpenPositions => (super.noSuchMethod(
        Invocation.getter(#maxOpenPositions),
        returnValue: 0,
      ) as int);

  @override
  bool get isLocked => (super.noSuchMethod(
        Invocation.getter(#isLocked),
        returnValue: false,
      ) as bool);

  @override
  _i5.Stream<bool> get safetyStream => (super.noSuchMethod(
        Invocation.getter(#safetyStream),
        returnValue: _i5.Stream<bool>.empty(),
      ) as _i5.Stream<bool>);

  @override
  Map<String, _i8.StrategyAuthorization> get authorizedStrategies =>
      (super.noSuchMethod(
        Invocation.getter(#authorizedStrategies),
        returnValue: <String, _i8.StrategyAuthorization>{},
      ) as Map<String, _i8.StrategyAuthorization>);

  @override
  double get maxAggregateRiskUsdt => (super.noSuchMethod(
        Invocation.getter(#maxAggregateRiskUsdt),
        returnValue: 0.0,
      ) as double);

  @override
  double get currentAggregateRiskUsdt => (super.noSuchMethod(
        Invocation.getter(#currentAggregateRiskUsdt),
        returnValue: 0.0,
      ) as double);

  @override
  _i5.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void authorizeStrategy(
    String? id,
    _i8.StrategyAuthorization? config,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #authorizeStrategy,
          [
            id,
            config,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void revokeStrategy(String? id) => super.noSuchMethod(
        Invocation.method(
          #revokeStrategy,
          [id],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setMaxAggregateRisk(double? limit) => super.noSuchMethod(
        Invocation.method(
          #setMaxAggregateRisk,
          [limit],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setDailyLossLimit(double? limit) => super.noSuchMethod(
        Invocation.method(
          #setDailyLossLimit,
          [limit],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setMaxOrderSize(double? limit) => super.noSuchMethod(
        Invocation.method(
          #setMaxOrderSize,
          [limit],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void activateEmergencyStop() => super.noSuchMethod(
        Invocation.method(
          #activateEmergencyStop,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void reset() => super.noSuchMethod(
        Invocation.method(
          #reset,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool validateOrder({
    required double? quantity,
    required double? priceUsdt,
    String? strategyId,
    bool? isLive = false,
    bool? isReduction = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #validateOrder,
          [],
          {
            #quantity: quantity,
            #priceUsdt: priceUsdt,
            #strategyId: strategyId,
            #isLive: isLive,
            #isReduction: isReduction,
          },
        ),
        returnValue: false,
      ) as bool);

  @override
  void incrementStrategyTradeCount(String? strategyId) => super.noSuchMethod(
        Invocation.method(
          #incrementStrategyTradeCount,
          [strategyId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void recordTradeResult(
    double? pnlUsdt, {
    String? strategyId,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #recordTradeResult,
          [pnlUsdt],
          {#strategyId: strategyId},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateAggregateRisk(double? deltaUsdt) => super.noSuchMethod(
        Invocation.method(
          #updateAggregateRisk,
          [deltaUsdt],
        ),
        returnValueForMissingStub: null,
      );

  @override
  Map<String, dynamic> getStatus() => (super.noSuchMethod(
        Invocation.method(
          #getStatus,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
